apiVersion: v1
kind: Service
metadata:
  name: {{ include "vikunja.apiFullname" . }}
  labels:
    {{- include "vikunja.labels" . | nindent 4 }}
spec:
  type: {{ .Values.api.service.type }}
  ports:
  - port: {{ int .Values.api.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "vikunja.apiSelectorLabels" . | nindent 4 }}
